### ISSUE TITLE
Parallels Tools out of date w/ PD 11 and boot2docker-1.8.1 image

### ISSUE THREAD

**Issue by y3ddet** [Parallels/docker-machine#2]
The latest/default image is boot2docker 1.8.1, and the boot console seems to indicate Parallels Tools pieces being added/run, but the GUI insists that tools are out of date.

The GUI actions to try and update tools will of course fail because it wants to mount the prlstools.iso image on the CDROM which is already connected to the boot2docker.iso image.

**Comment by legal90** [comment]
Unlikely other guest systems, in boot2docker we have Parallels Tools preinstalled and currently they are a little bit outdated: https://github.com/boot2docker/boot2docker/pull/954
There is a special build of Parallels Tools and since it is bundled with boot2docker.iso, it could not be updated by the traditional way.

Parallels Desktop detects that tools version is different and shows yellow "!" label, which looks confusing. So, let it be a known issue. 
But in fact, these Parallels Tools are functioning correctly. Please ignore the warning in GUI.

P.s. Probably, this behavior will be improved in the future, with Docker Machine 0.5.0.

**Comment by y3ddet** [comment]
@legal90 that makes sense, the issue however is that the PD support folks insist on trying to get the PD tools updated, and since that doesn't work, they claim the whole caboodle is "unsupported" - any chance you could get the PD Knowledge Base article that points to this copy of docker-machine to note the discrepancy?

**Comment by legal90** [comment]
I'm sorry for a later update - in Parallels Desktop 11.0.1 this issue have been worked around:
For boo2docker guests the Parallels Tools status is not displayed as outdated and "Update" button has been removed from the GUI. 

@y3ddet Thanks again for catching this!
